### ISSUE TITLE
GPT-4 results?

### ISSUE THREAD

**Issue by jeasung-park** [cambridgeltl/zepo#1]
Hello,
Is there any quantitative results coming from GPT-4 or Gemini-Pro?

Thanks for the great research.

**Comment by hanzhou032** [comment]
Hi,

Thanks for the interest to our project! Currently, GPT-4 is too costly to conduct pairwise evaluations so we have only focused on opensource 7B models yet. We will endeavor to include Gemini-pro in the future and keep it updated.
